// @flow

export const FETCH_BEES_REQUEST: string = "BEES/FETCH_BEES_REQUEST";
export const BEES_RECEIVED: string = "BEES/BEES_RECEIVED";
export const BEES_REQUEST_FAILED: string = "BEES/BEES_REQUEST_FAILED";

export const CREATE_BEE_REQUEST: string = "BEES/CREATE_BEE_REQUEST";
export const CREATE_BEE_SUCCESSFUL: string = "BEES/CREATE_BEE_SUCCESSFUL";
export const CREATE_BEE_FAILED: string = "BEES/CREATE_BEE_FAILED";

export const REMOVE_ALL_BEES_REQUEST: string = "BEES/REMOVE_ALL_BEES_REQUEST";
export const REMOVE_ALL_BEES_SUCCESSFUL: string =
  "BEES/REMOVE_ALL_BEES_SUCCESSFUL";
export const REMOVE_ALL_BEES_FAILED: string = "BEES/REMOVE_ALL_BEES_FAILED";

export const REMOVE_BEE_REQUEST: string = "BEES/REMOVE_BEE_REQUEST";
export const REMOVE_BEE_SUCCESSFUL: string = "BEES/REMOVE_BEE_SUCCESSFUL";
export const REMOVE_BEE_FAILED: string = "BEES/REMOVE_BEE_FAILED";
